# generated by datamodel-codegen:
#   filename:  profile/answers.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class AnswersFile(BaseModel):
    """
    answers.yaml: standard application answers plus header fields name, email, phone, location, links.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    answers: dict[str, str]
