# generated by datamodel-codegen:
#   filename:  profile/bases.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ResumeBase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9-]*$')]
    name: str
    block_ids: list[str]
    section_order: list[str] = [
        'summary',
        'experience',
        'projects',
        'skills',
        'credentials',
    ]
    style: dict[str, Any] = {}


class BasesFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bases: list[ResumeBase]
