# generated by datamodel-codegen:
#   filename:  profile/blocks.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Visibility(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exclude_when: list[str] = []
    """
    Context tags that hard-exclude this block from a tailoring run.
    """


class Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9-]*$')]
    type: Literal['achievement', 'role', 'project', 'skill', 'credential']
    org: str | None = None
    role: str | None = None
    period: Annotated[
        str | None,
        Field(
            pattern='^(?:(?:[Jj]an|[Ff]eb|[Mm]ar|[Aa]pr|[Mm]ay|[Jj]un|[Jj]ul|[Aa]ug|[Ss]ep|[Oo]ct|[Nn]ov|[Dd]ec)[a-z]*\\.?\\s+)?\\d{4}(?:\\s*(?:[-‒–—−]|to)\\s*(?:(?:(?:[Jj]an|[Ff]eb|[Mm]ar|[Aa]pr|[Mm]ay|[Jj]un|[Jj]ul|[Aa]ug|[Ss]ep|[Oo]ct|[Nn]ov|[Dd]ec)[a-z]*\\.?\\s+)?\\d{4}|[Pp]resent|[Cc]urrent|[Nn]ow))?$'
        ),
    ] = None
    """
    YYYY, YYYY-YYYY, or YYYY-Present, each year optionally prefixed by a month (Mar 2019 - Present)
    """
    verified: bool = False
    """
    Only verified blocks may carry metrics.
    """
    metric: str | None = None
    content: str
    tags: list[str] = []
    attribution: str | None = None
    """
    Required attribution phrase for named projects.
    """
    concurrent: bool = False
    """
    May overlap in time with other roles.
    """
    visibility: Visibility | None = None


class BlocksFile(BaseModel):
    """
    blocks.yaml: the user's provenance-checked resume block library.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[Block]
