# generated by datamodel-codegen:
#   filename:  profile/blocks.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Visibility(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exclude_when: list[str] = []
    """
    Context tags that hard-exclude this block from a tailoring run.
    """


class Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9-]*$')]
    type: Literal['achievement', 'role', 'project', 'skill', 'credential']
    org: str | None = None
    role: str | None = None
    period: str | None = None
    """
    YYYY, YYYY-YYYY, or YYYY-Present
    """
    verified: bool = False
    """
    Only verified blocks may carry metrics.
    """
    metric: str | None = None
    content: str
    tags: list[str] = []
    attribution: str | None = None
    """
    Required attribution phrase for named projects.
    """
    concurrent: bool = False
    """
    May overlap in time with other roles.
    """
    visibility: Visibility | None = None


class BlocksFile(BaseModel):
    """
    blocks.yaml: the user's provenance-checked resume block library.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[Block]
