# generated by datamodel-codegen:
#   filename:  profile/guardrails.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class GuardrailRule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rule: str
    active: bool = True
    config: dict[str, Any] = {}


class GuardrailsFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    guardrails: list[GuardrailRule]
