# generated by datamodel-codegen:
#   filename:  profile/tracks.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Track(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9-]*$')]
    name: str
    description: str | None = None
    keywords: list[str] | None = []
    resume_base: str
    min_fit: Annotated[int | None, Field(ge=0, le=100)] = 50


class TracksFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tracks: list[Track]
