# generated by datamodel-codegen:
#   filename:  profile/watchlist.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class WatchlistEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    company: str
    source: Literal['greenhouse', 'lever', 'ashby', 'smartrecruiters', 'workable']
    board: str
    keywords: list[str] = []


class AggregatorEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['remoteok', 'hn-hiring']
    enabled: bool = True
    keywords: list[str] = []


class WatchlistFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    watchlist: list[WatchlistEntry]
    aggregators: Annotated[list[AggregatorEntry], Field(validate_default=True)] = []
