# generated by datamodel-codegen:
#   filename:  profile/watchlist.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class WatchlistEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    company: str
    source: Literal['greenhouse', 'lever', 'ashby', 'smartrecruiters', 'workable']
    board: str


class WatchlistFile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    watchlist: list[WatchlistEntry]
