/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Board */
        get: operations["board_api_v1_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        /** Delete Application */
        delete: operations["delete_application_api_v1_applications__application_id__delete"];
        options?: never;
        head?: never;
        /** Patch Application */
        patch: operations["patch_application_api_v1_applications__application_id__patch"];
        trace?: never;
    };
    "/api/v1/discovery/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll */
        post: operations["poll_api_v1_discovery_poll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discovery/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_discovery_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discovery/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_v1_discovery_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_api_v1_jobs__job_id__packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/rescue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescue Job */
        post: operations["rescue_job_api_v1_jobs__job_id__rescue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tailor Job Endpoint */
        post: operations["tailor_job_endpoint_api_v1_jobs__job_id__tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Packages */
        get: operations["list_all_packages_api_v1_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package */
        get: operations["get_package_api_v1_packages__package_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Package
         * @description Human edit -> re-validate -> re-render -> new version. Never bypasses guardrails.
         *
         *     Blocks-mode packages are patched with `resume` and re-run through `run_guardrails` with the
         *     parent's stored selection; tune-mode packages are patched with `edits` and re-run through
         *     `run_tune_guardrails` against the uploaded document. The body must match the parent's mode:
         *     a resume has no meaning for a tuned document, and vice versa.
         */
        patch: operations["patch_package_api_v1_packages__package_id__patch"];
        trace?: never;
    };
    "/api/v1/packages/{package_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Package */
        get: operations["download_package_api_v1_packages__package_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packages/{package_id}/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Package File */
        get: operations["package_file_api_v1_packages__package_id__files__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/aggregators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Aggregators */
        get: operations["get_aggregators_api_v1_profile_aggregators_get"];
        /** Put Aggregators */
        put: operations["put_aggregators_api_v1_profile_aggregators_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Answers */
        get: operations["get_answers_api_v1_profile_answers_get"];
        /** Put Answers */
        put: operations["put_answers_api_v1_profile_answers_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bases */
        get: operations["list_bases_api_v1_profile_bases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/bases/{base_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Base */
        put: operations["put_base_api_v1_profile_bases__base_id__put"];
        post?: never;
        /** Delete Base */
        delete: operations["delete_base_api_v1_profile_bases__base_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blocks */
        get: operations["list_blocks_api_v1_profile_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Block */
        put: operations["put_block_api_v1_profile_blocks__block_id__put"];
        post?: never;
        /** Delete Block */
        delete: operations["delete_block_api_v1_profile_blocks__block_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Profile */
        get: operations["export_profile_api_v1_profile_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/guardrails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Guardrails */
        get: operations["list_guardrails_api_v1_profile_guardrails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/guardrails/{rule}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Guardrail */
        put: operations["put_guardrail_api_v1_profile_guardrails__rule__put"];
        post?: never;
        /** Delete Guardrail */
        delete: operations["delete_guardrail_api_v1_profile_guardrails__rule__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Profile */
        post: operations["import_profile_api_v1_profile_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/resume-document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume Document */
        get: operations["get_resume_document_api_v1_profile_resume_document_get"];
        put?: never;
        /**
         * Upload Resume Document
         * @description Accept one .docx, parse it, and keep it as the document tune mode rewrites.
         *
         *     The bytes go to the storage volume, never into git and never into the package row; only
         *     the parsed paragraphs are stored in Postgres.
         */
        post: operations["upload_resume_document_api_v1_profile_resume_document_post"];
        /**
         * Delete Document
         * @description Idempotent: deleting nothing is still a 204, and tailoring falls back to blocks mode.
         */
        delete: operations["delete_document_api_v1_profile_resume_document_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tracks */
        get: operations["list_tracks_api_v1_profile_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Track */
        put: operations["put_track_api_v1_profile_tracks__track_id__put"];
        post?: never;
        /** Delete Track */
        delete: operations["delete_track_api_v1_profile_tracks__track_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_api_v1_profile_watchlist_get"];
        /** Put Watchlist */
        put: operations["put_watchlist_api_v1_profile_watchlist_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Events */
        get: operations["task_events_api_v1_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AggregatorEntry */
        AggregatorEntry: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /**
             * Source
             * @enum {string}
             */
            source: "remoteok" | "hn-hiring";
        };
        /** ApplicationCreate */
        ApplicationCreate: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Package Id */
            package_id?: string | null;
        };
        /** ApplicationOut */
        ApplicationOut: {
            /** Applied At */
            applied_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            job: components["schemas"]["JobRef"];
            /** Notes */
            notes: string;
            /** Package Id */
            package_id: string | null;
            /** Status */
            status: string;
            /** Status History */
            status_history: components["schemas"]["StatusChange"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ApplicationPatch */
        ApplicationPatch: {
            /** Notes */
            notes?: string | null;
            /** Status */
            status?: string | null;
        };
        /** Block */
        Block: {
            /** Attribution */
            attribution?: string | null;
            /**
             * Concurrent
             * @default false
             */
            concurrent: boolean;
            /** Content */
            content: string;
            /** Id */
            id: string;
            /** Metric */
            metric?: string | null;
            /** Org */
            org?: string | null;
            /** Period */
            period?: string | null;
            /** Role */
            role?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Type
             * @enum {string}
             */
            type: "achievement" | "role" | "project" | "skill" | "credential";
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            visibility?: components["schemas"]["Visibility"] | null;
        };
        /** BoardOut */
        BoardOut: {
            /** Columns */
            columns: {
                [key: string]: components["schemas"]["ApplicationOut"][];
            };
        };
        /** Body_import_profile_api_v1_profile_import_post */
        Body_import_profile_api_v1_profile_import_post: {
            /** Files */
            files: string[];
        };
        /** Body_upload_resume_document_api_v1_profile_resume_document_post */
        Body_upload_resume_document_api_v1_profile_resume_document_post: {
            /** File */
            file: string;
        };
        /** DocParagraph */
        DocParagraph: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "name" | "contact" | "heading" | "summary" | "competency" | "entry_title" | "entry_org" | "bullet" | "skill" | "credential" | "other";
            /** Section */
            section?: string | null;
            /** Text */
            text: string;
        };
        /** DocSection */
        DocSection: {
            /** Heading */
            heading: string;
            /** Paragraph Ids */
            paragraph_ids: string[];
        };
        /** Edit */
        Edit: {
            /** After */
            after: string;
            /** Before */
            before: string;
            /** Paragraph Id */
            paragraph_id: string;
            /** Reason */
            reason: string;
        };
        /**
         * EditPatch
         * @description One paragraph the human rewrote. `before` is not accepted: the stored document is the
         *     only authority on what the paragraph said.
         */
        EditPatch: {
            /** After */
            after: string;
            /** Paragraph Id */
            paragraph_id: string;
        };
        /** GuardrailReport */
        GuardrailReport: {
            /** Passed */
            passed: boolean;
            /** Rules Run */
            rules_run: string[];
            /** Violations */
            violations: components["schemas"]["Violation"][];
        };
        /** GuardrailRule */
        GuardrailRule: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Config
             * @default {}
             */
            config: {
                [key: string]: unknown;
            };
            /** Rule */
            rule: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** ImportOut */
        ImportOut: {
            /** Bases */
            bases: number;
            /** Blocks */
            blocks: number;
            /** Guardrails */
            guardrails: number;
            /** Tracks */
            tracks: number;
        };
        /**
         * JDExtract
         * @description Structured requirements extracted from a job description.
         */
        JDExtract: {
            /** Company */
            company: string;
            /**
             * Context Tags
             * @default []
             */
            context_tags: string[];
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /**
             * Likely Knockouts
             * @default []
             */
            likely_knockouts: string[];
            /**
             * Location Policy
             * @default unspecified
             */
            location_policy: string;
            /**
             * Must Have
             * @default []
             */
            must_have: string[];
            /**
             * Nice To Have
             * @default []
             */
            nice_to_have: string[];
            /**
             * Seniority
             * @default unspecified
             */
            seniority: string;
            /** Title */
            title: string;
        };
        /** JobCreate */
        JobCreate: {
            /** Company */
            company?: string | null;
            /** Jd Text */
            jd_text?: string | null;
            /** Location */
            location?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /** JobOut */
        JobOut: {
            /** Application Status */
            application_status: string | null;
            /** Best Fit */
            best_fit?: number | null;
            /** Best Track Id */
            best_track_id?: string | null;
            /** Bucket */
            bucket?: ("fit" | "low") | null;
            /** Company */
            company: string | null;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
            extracted: components["schemas"]["JDExtract"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Jd Text */
            jd_text: string;
            latest_package: components["schemas"]["PackageSummary"] | null;
            /** Location */
            location: string | null;
            /** Posted At */
            posted_at?: string | null;
            /** Repost Of */
            repost_of?: string | null;
            /**
             * Rescued
             * @default false
             */
            rescued: boolean;
            /**
             * Scores
             * @default []
             */
            scores: components["schemas"]["JobScoreOut"][];
            /** Source */
            source: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string | null;
        };
        /** JobRef */
        JobRef: {
            /** Company */
            company: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
        };
        /** JobScoreOut */
        JobScoreOut: {
            /** Fit Score */
            fit_score: number;
            /** Rationale */
            rationale: {
                [key: string]: unknown;
            };
            /** Track Id */
            track_id: string;
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** PackageListItem */
        PackageListItem: {
            /** Application Status */
            application_status: string | null;
            /** Best Fit */
            best_fit: number | null;
            /** Best Track Id */
            best_track_id: string | null;
            /** Company */
            company: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "blocks" | "tune";
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Version */
            version: number;
        };
        /** PackageOut */
        PackageOut: {
            /** Answers */
            answers: {
                [key: string]: string;
            };
            /** Change Log */
            change_log: string;
            /** Cover Note */
            cover_note: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Edits */
            edits: components["schemas"]["Edit"][];
            guardrail_report: components["schemas"]["GuardrailReport"];
            /** Has Docx */
            has_docx: boolean;
            /** Has Pdf */
            has_pdf: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            jd_extract: components["schemas"]["JDExtract"];
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Llm Calls */
            llm_calls: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "blocks" | "tune";
            /** Parent Package Id */
            parent_package_id: string | null;
            resume: components["schemas"]["ResumeDocument"];
            source_document: components["schemas"]["SourceDocument"] | null;
            /** Status */
            status: string;
            /** Track Id */
            track_id: string;
            /** Version */
            version: number;
        };
        /**
         * PackagePatch
         * @description A human edit to a package: `resume` in blocks mode, `edits` in tune mode.
         *
         *     Each field carries the complete new state for its mode, not a delta, so a new version is
         *     always a full replacement of the thing the mode owns.
         */
        PackagePatch: {
            /** Edits */
            edits?: components["schemas"]["EditPatch"][] | null;
            resume?: components["schemas"]["ResumeDocument"] | null;
        };
        /** PackageSummary */
        PackageSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "blocks" | "tune";
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /** PollRunOut */
        PollRunOut: {
            /** Board */
            board: string | null;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Found */
            found: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** New */
            new: number;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** ResumeBase */
        ResumeBase: {
            /** Block Ids */
            block_ids: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Section Order
             * @default [
             *       "summary",
             *       "experience",
             *       "projects",
             *       "skills",
             *       "credentials"
             *     ]
             */
            section_order: string[];
            /**
             * Style
             * @default {}
             */
            style: {
                [key: string]: unknown;
            };
        };
        /** ResumeBullet */
        ResumeBullet: {
            /** Source Block Id */
            source_block_id: string;
            /** Text */
            text: string;
        };
        /**
         * ResumeDocument
         * @description A tailored resume. Every bullet and entry cites the block it came from.
         */
        ResumeDocument: {
            header: components["schemas"]["ResumeHeader"];
            /** Sections */
            sections: components["schemas"]["ResumeSection"][];
            /**
             * Summary
             * @default []
             */
            summary: components["schemas"]["ResumeBullet"][];
        };
        /** ResumeDocumentOut */
        ResumeDocumentOut: {
            document: components["schemas"]["SourceDocument"];
            /** Filename */
            filename: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** ResumeEntry */
        ResumeEntry: {
            /**
             * Bullets
             * @default []
             */
            bullets: components["schemas"]["ResumeBullet"][];
            /** Org */
            org?: string | null;
            /** Period */
            period?: string | null;
            /** Role */
            role?: string | null;
            /** Source Block Id */
            source_block_id: string;
            /** Title */
            title?: string | null;
        };
        /** ResumeHeader */
        ResumeHeader: {
            /** Email */
            email?: string | null;
            /**
             * Links
             * @default []
             */
            links: string[];
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
        };
        /** ResumeSection */
        ResumeSection: {
            /** Entries */
            entries: components["schemas"]["ResumeEntry"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "experience" | "projects" | "skills" | "credentials";
            /** Title */
            title: string;
        };
        /** SourceDocument */
        SourceDocument: {
            /** Filename */
            filename: string;
            /** Paragraphs */
            paragraphs: components["schemas"]["DocParagraph"][];
            /** Sections */
            sections: components["schemas"]["DocSection"][];
        };
        /** SourceInfoOut */
        SourceInfoOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "board" | "aggregator";
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Needs Board */
            needs_board: boolean;
        };
        /** StatusChange */
        StatusChange: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Status */
            status: string;
        };
        /** TailorBody */
        TailorBody: {
            /** Feedback */
            feedback?: string | null;
            /** Mode */
            mode?: ("blocks" | "tune") | null;
            /** Parent Package Id */
            parent_package_id?: string | null;
            /** Track Id */
            track_id?: string | null;
        };
        /** TaskOut */
        TaskOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Result Ref */
            result_ref: string | null;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /** Track */
        Track: {
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /**
             * Min Fit
             * @default 50
             */
            min_fit: number;
            /** Name */
            name: string;
            /** Resume Base */
            resume_base: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Violation */
        Violation: {
            /** Block Id */
            block_id?: string | null;
            /** Message */
            message: string;
            /** Path */
            path: string;
            /** Rule */
            rule: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
        };
        /** Visibility */
        Visibility: {
            /**
             * Exclude When
             * @default []
             */
            exclude_when: string[];
        };
        /** WatchlistEntry */
        WatchlistEntry: {
            /** Board */
            board: string;
            /** Company */
            company: string;
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /**
             * Source
             * @enum {string}
             */
            source: "greenhouse" | "lever" | "ashby" | "smartrecruiters" | "workable";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    board_api_v1_applications_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description This job already has an application */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_v1_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_application_api_v1_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_api_v1_discovery_poll_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_v1_discovery_runs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_v1_discovery_sources_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceInfoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                search?: string | null;
                track?: string | null;
                bucket?: ("fit" | "low") | null;
                sort?: "fit" | "newest";
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description A job with the same description already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packages_api_v1_jobs__job_id__packages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescue_job_api_v1_jobs__job_id__rescue_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tailor_job_endpoint_api_v1_jobs__job_id__tailor_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailorBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_packages_api_v1_packages_get: {
        parameters: {
            query?: {
                status?: ("draft" | "blocked") | null;
                applied?: boolean | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_package_api_v1_packages__package_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_package_api_v1_packages__package_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackagePatch"];
            };
        };
        responses: {
            /** @description A new package version was created */
            201: {
                headers: {
                    /** @description URL of the newly created package version */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_package_api_v1_packages__package_id__download_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    package_file_api_v1_packages__package_id__files__name__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                package_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_aggregators_api_v1_profile_aggregators_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregatorEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_aggregators_api_v1_profile_aggregators_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AggregatorEntry"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregatorEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_answers_api_v1_profile_answers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_answers_api_v1_profile_answers_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bases_api_v1_profile_bases_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeBase"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_base_api_v1_profile_bases__base_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeBase"];
            };
        };
        responses: {
            /** @description The base already existed and was replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeBase"];
                };
            };
            /** @description The base was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_base_api_v1_profile_bases__base_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blocks_api_v1_profile_blocks_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_block_api_v1_profile_blocks__block_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Block"];
            };
        };
        responses: {
            /** @description The block already existed and was replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            /** @description The block was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_block_api_v1_profile_blocks__block_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                block_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_profile_api_v1_profile_export_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_guardrails_api_v1_profile_guardrails_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailRule"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_guardrail_api_v1_profile_guardrails__rule__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                rule: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuardrailRule"];
            };
        };
        responses: {
            /** @description The guardrail rule already existed and was replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailRule"];
                };
            };
            /** @description The guardrail rule was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardrailRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_guardrail_api_v1_profile_guardrails__rule__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                rule: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_profile_api_v1_profile_import_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_profile_api_v1_profile_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_document_api_v1_profile_resume_document_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_document_api_v1_profile_resume_document_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_document_api_v1_profile_resume_document_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_profile_resume_document_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tracks_api_v1_profile_tracks_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_track_api_v1_profile_tracks__track_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Track"];
            };
        };
        responses: {
            /** @description The track already existed and was replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description The track was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_track_api_v1_profile_tracks__track_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_api_v1_profile_watchlist_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_watchlist_api_v1_profile_watchlist_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistEntry"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_events_api_v1_tasks__task_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
