# generated by datamodel-codegen:
#   filename:  guardrail_report.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class Violation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rule: str
    severity: Literal['error', 'warning']
    message: str
    path: str
    """
    e.g. sections[0].entries[1].bullets[2]
    """
    block_id: str | None = None


class GuardrailReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    passed: bool
    rules_run: list[str]
    violations: list[Violation]
