# generated by datamodel-codegen:
#   filename:  jd_extract.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class JDExtract(BaseModel):
    """
    Structured requirements extracted from a job description.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    company: str
    title: str
    location_policy: str | None = 'unspecified'
    """
    remote, hybrid, onsite, or unspecified
    """
    seniority: str | None = 'unspecified'
    must_have: list[str] | None = []
    nice_to_have: list[str] | None = []
    keywords: list[str] | None = []
    likely_knockouts: list[str] | None = []
    context_tags: list[str] | None = []
    """
    Tags matched against block visibility.exclude_when
    """
