# generated by datamodel-codegen:
#   filename:  package.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import guardrail_report as guardrail_report_1
from . import jd_extract as jd_extract_1
from . import resume_document


class JobSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    company: str
    title: str
    location: str | None = None
    url: str | None = None
    jd_text: str


class ApplicationPackage(BaseModel):
    """
    Everything produced for one application, versioned.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    job: JobSnapshot
    track_id: str
    jd_extract: jd_extract_1.JDExtract
    resume: resume_document.ResumeDocument
    cover_note: str
    change_log: str
    answers: dict[str, str]
    guardrail_report: guardrail_report_1.GuardrailReport
    version: Annotated[int, Field(ge=1)]
    status: Literal['draft', 'blocked']
    llm_calls: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
