# generated by datamodel-codegen:
#   filename:  package.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import guardrail_report as guardrail_report_1
from . import jd_extract as jd_extract_1
from . import resume_document
from . import source_document as source_document_1


class JobSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    company: str
    title: str
    location: str | None = None
    url: str | None = None
    jd_text: str


class TokenUsage(BaseModel):
    """
    LLM token usage for one call or the sum of several. Mirrors rhapto.engine.providers.llm.TokenUsage field for field; the pipeline sums the engine type into this one when it builds the package.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    input_tokens: Annotated[int, Field(ge=0)] = 0
    output_tokens: Annotated[int, Field(ge=0)] = 0
    cache_read_input_tokens: Annotated[int, Field(ge=0)] = 0
    cache_creation_input_tokens: Annotated[int, Field(ge=0)] = 0


class ApplicationPackage(BaseModel):
    """
    Everything produced for one application, versioned.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    job: JobSnapshot
    usage: TokenUsage
    model: str | None = None
    track_id: str
    jd_extract: jd_extract_1.JDExtract
    resume: resume_document.ResumeDocument
    cover_note: str
    change_log: str
    answers: dict[str, str]
    guardrail_report: guardrail_report_1.GuardrailReport
    version: Annotated[int, Field(ge=1)]
    status: Literal['draft', 'ready', 'blocked']
    llm_calls: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    mode: Literal['blocks', 'tune'] = 'blocks'
    edits: Annotated[list[source_document_1.Edit], Field(validate_default=True)] = []
    source_document: source_document_1.SourceDocument | None = None
