# generated by datamodel-codegen:
#   filename:  resume_document.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class ResumeHeader(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    email: str | None = None
    phone: str | None = None
    location: str | None = None
    links: list[str] = []


class ResumeBullet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    source_block_id: str


class ResumeEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_block_id: str
    org: str | None = None
    role: str | None = None
    period: str | None = None
    title: str | None = None
    bullets: Annotated[list[ResumeBullet], Field(validate_default=True)] = []


class ResumeSection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    kind: Literal['experience', 'projects', 'skills', 'credentials']
    entries: list[ResumeEntry]


class ResumeDocument(BaseModel):
    """
    A tailored resume. Every bullet and entry cites the block it came from.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    header: ResumeHeader
    summary: Annotated[list[ResumeBullet], Field(validate_default=True)] = []
    sections: list[ResumeSection]
