# generated by datamodel-codegen:
#   filename:  source_document.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class DocParagraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(pattern='^p[0-9]+$')]
    text: str
    role: Literal[
        'name',
        'contact',
        'heading',
        'summary',
        'competency',
        'entry_title',
        'entry_org',
        'bullet',
        'skill',
        'credential',
        'other',
    ]
    section: str | None = None


class DocSection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    heading: str
    paragraph_ids: list[str]


class Edit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    paragraph_id: str
    before: str
    after: str
    reason: str


class SourceDocument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filename: str
    paragraphs: list[DocParagraph]
    sections: list[DocSection]
