# generated by datamodel-codegen:
#   filename:  taxonomy.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class TaxonomyRole(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9-]*$')]
    name: str
    keywords: Annotated[list[str], Field(max_length=10, min_length=6)]
    titles: list[str] = []
    """
    Job-title phrases that mean this role. Whole-word, case-insensitive; a space also matches a hyphen.
    """
    exclude_titles: list[str] = []
    """
    Words or phrases that, present in a title, mean it is NOT this role even though a titles phrase matched.
    """


class TaxonomyField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9-]*$')]
    name: str
    themuse_category: str
    adzuna_category: str
    roles: Annotated[list[TaxonomyRole], Field(min_length=1)]


class TaxonomyFile(BaseModel):
    """
    taxonomy.yaml: career fields, the roles inside them, the keywords a track starts from, and the category name each aggregator uses for the field.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    fields: Annotated[list[TaxonomyField], Field(min_length=1)]
